### ISSUE TITLE
Remember the day when reopening the app

### ISSUE THREAD

**Issue by steffchep** [dukecon/dukecon_pwa#45] opened 2018-03-14 14:18 UTC
Every time the web app is opened, it goes to the first day. Remember where I was when I closed it and start the app with the appropriate day open (this is a regression from the HTML5-project)

**Comment by sippsack** [comment] 2018-03-14 14:24
and scroll to the current time slot?

**Comment by ascheman** [comment] 2018-03-14 14:27
This seems to be a duplicate of #44 ;-)

**Comment by steffchep** [comment] 2018-03-14 14:33
@Falk - sceol to where I was last, yes :)

@Gerd Not quite - #44 implies automatic - this is about where the user was last time ;)

**Comment by ahus1** [comment] 2018-03-15 11:28
IMHO: The current day should be encoded in the URL ... this way the browser will memorize it automatically, and you can even send it via a link / share it.

**Comment by ahus1** [comment] 2018-03-16 21:47
@steffchep @sippsack - ready to review on https://latest.dukecon.org/javaland/2018/#/schedule/2018-03-14

**Comment by ahus1** [comment] 2018-04-21 18:49
waiting for review for one month. closing due to timeout.

**Closed as completed by ahus1** 2018-04-21 18:49 UTC
